### ISSUE TITLE
Update RHIPE function documentation

### ISSUE THREAD

**Issue by hafen** [tesseradata/RHIPE#20]
@XiaosuTong, @wscpurdue: The RHIPE function documentation has some flaws.  For example, the very first example one sees for `rhwatch()` calls for `mapred=mapred` but `mapred` has not been defined.  Not a good way to be introduced to `rhwatch()`.

https://github.com/tesseradata/RHIPE/blob/master/src/main/R/rhwatch.R#L230

In general, it would be good to go through all the examples and make sure they are working and up-to-date.

**Comment by XiaosuTong** [comment]
@hafen, @wscpurdue: Yeah, that is right. I will be on this thread.

**Comment by hafen** [comment]
@XiaosuTong thanks!

**Comment by XiaosuTong** [comment]
@hafen I have gone through all functions documation, and updated all examples and some
discriptions. This thread can be closed

Xiaosu
