### ISSUE TITLE
Cannot load package Matrix?

### ISSUE THREAD

**Issue by andrewzm** [tesseradata/RHIPE#28]
Hi, I seem to be having trouble attaching the package "Matrix" needed for a map operation. I get some vague error message in the R console:

    There were R errors, showing 30:
    Attaching package: ‘Matrix’
    Autokill is true and terminating job_201505051410_0252

**Reproduce**: This happens just when attaching the package. For example:

    map1 <- expression({
        library(Matrix)
        lapply(seq_along(map.keys), function(r) {
           outputkey = r
           outputvalue = 1
           rhcollect(outputkey, outputvalue)
        })
    })

    mapreduce1 <- rhwatch(
        map      = map1,
        input    = 10,
        output   = rhfmt("reduced_data", type = "sequence"),
        mapred   = list(mapred.map.tasks=10,
			        mapred.reduce.tasks=0),
        readback = TRUE )

will generate this error. 

**Other symptoms**: I have no other symptoms and Rhipe is working brilliantly otherwise. I am attaching other packages and weirdly enough if I do an operation

    Matrix::Matrix()

then no error is thrown. So it is something specific to the loading of the Matrix package (I think). Any ideas?

**Comment by hafen** [comment]
It looks like your version of the Matrix package is providing a startup message (it doesn't happen on my end).  Try the following:

```
suppressMessages(library(Matrix))
```

**Comment by andrewzm** [comment]
I had tried `library(Matrix,quietly==TRUE)` but that didn't help. This did the trick though,thanks!
