### ISSUE TITLE
rhipe_map_buff_size or rhipe_map_buffsize

### ISSUE THREAD

**Issue by jrounds** [tesseradata/RHIPE#31]
At various points in the documentation it refers to both of these ^^^  I am not sure which it is.

For example:
```
If a task consists of W key,value pairs, the expression map will be called ceil(W / rhipe_map_buffsize) times. The default value of rhipe_map_buff_size is...
```

**Comment by hafen** [comment]
It's `buff_size`.  I thought we had taken care of that - thanks for pointing it out.  I'll push a fix (everything works right now - just typos in the docs).
