### ISSUE TITLE
RHIPE incompatible with jsonlite?

### ISSUE THREAD

**Issue by rundel** [tesseradata/RHIPE#33]
I've run into an issue when I attempt to use the jsonlite package inside of my map function - running the following minimal code (after initializing Rhipe including setting the zips and runner options) results in the errors I've included below. If I comment out `library(jsonlite)` everything runs fine and swapping to other compiled third party libraries like `Rcpp` works fine.

```
data = list(list("a",1),list("b",2))
rhwrite(data, "/tmp/data")


reduce = expression(
  pre = {
    total = 0
  },
  reduce = {
    total = total + 1
  },
  post = {
    rhcollect(reduce.key, total)
  }
)

map = expression({
  library(jsonlite)
  rhcollect("test",1)
})


rhwatch(
  map      = map,
  reduce   = reduce,
  input    = rhfmt("/tmp/data",type="sequence")
)
```

R output:

```
[Thu Nov 19 19:54:52 2015] Name:2015-11-19 19:54:52 Job: job_1447794649899_0075  State: PREP Duration: 0.063
URL: http://saxon.stat.duke.edu:8088/proxy/application_1447794649899_0075/
       pct numtasks pending running complete killed failed_attempts killed_attempts
map      0        0       0       0        0      0               0               0
reduce   0        0       0       0        0      0               0               0
Waiting 5 seconds
[Thu Nov 19 19:54:57 2015] Name:2015-11-19 19:54:52 Job: job_1447794649899_0075  State: RUNNING Duration: 5.291
URL: http://saxon.stat.duke.edu:8088/proxy/application_1447794649899_0075/
       pct numtasks pending running complete killed failed_attempts killed_attempts
map      0        1       1       0        0      0               0               0
reduce   0        1       1       0        0      0               0               0
Waiting 5 seconds

---------------------------------
There were R errors, showing 30:


Attaching package: ‘jsonlite’

Autokill is true and terminating job_1447794649899_0075
Warning message:
In Rhipe:::rhwatch.runner(job = job, mon.sec = mon.sec, readback = readback,  :
  Job failure, deleting output: /tmp/rhipe-temp-5bc9e459e050497bc7a760fe6dfcf5a6:
```

`cat(out[[1]]$errors)`:
```
Error: java.io.IOException: MROutput/MRErrThread failed:java.lang.RuntimeException: 
R ERROR BEGIN (map):
=============


Attaching package: ‘jsonlite’


R ERROR END
===========

	at org.godhuli.rhipe.RHMRHelper$MRErrorThread.run(RHMRHelper.java:459)

	at org.godhuli.rhipe.RHMRHelper.checkOuterrThreadsThrowable(RHMRHelper.java:329)
	at org.godhuli.rhipe.RHMRMapper.run(RHMRMapper.java:71)
	at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:787)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:341)
	at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:164)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:415)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1657)
	at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:158)
```

**Comment by hafen** [comment]
This is a common issue with loading packages inside a RHIPE job - any output printed by R is interpreted as an error by hadoop.  The way to make it work is to change it to `suppressMessages(library(jsonlite))`.

**Comment by saptarshiguha** [comment]
jsonlite, when being loaded emits message

> library(jsonlite)

Attaching package: ‘jsonlite’

The following object is masked from ‘package:utils’:

    View

>

These messages are sent to the error stream and get considered as errors.

Do this

suppressPackageStartupMessages(library(jsonlite))

It ought to work
Cheers
Saptarshi

**Comment by rundel** [comment]
Thanks for the quick feedback, this fixed things for me. In retrospect I remember coming across this warning somewhere when I was reading about RHIPE, but I don't think it was in the tutorial anywhere.

This seems like less than ideal behavior, is there a reason each call to map or reduce is no wrapped with sink by default?

**Comment by saptarshiguha** [comment]
Mostly possible performance reasons. The C code, buffers key-value input
and hands it to user code without much fuss inside.

Currently the C code handles all output going to stderr as an error (e.g.
'stop' sends messages to stderr)

Sink would add another wrapper around the code and possibly (not sure if at
all) affect the performance.

Options include using substitute/bquote to wrap templates around the code.
See what happens when the user passes a function to the map or better see
rhoptions()$template for examples about wrapping around the code in the
reduce section.

Regards
Saptarshi

**Comment by saptarshiguha** [comment]
hello,

In

https://github.com/tesseradata/RHIPE/blob/master/src/main/C/display.cc#L47

Supposedly,  oType is 0 for normal output,1 for information, 2 for warning
and 3 for error
The code has only ever seen 0 or 1 for oType. Maybe we're doing something
wrong?

Point being, we could have a flag to not treat otype = 1,2 as errors. That
would fix your issue.

Cheers
Saptarshi
