### ISSUE TITLE
Conflict between Rhipe md5 code and digest library md5 code

### ISSUE THREAD

**Issue by amwhite** [tesseradata/RHIPE#37]
There is a reproducible error in Rhipe that results in non-unique hashes of the keys in
datadr ddf and ddo objects. The issue appears to be a conflict between the C md5 functions in
Rhipe and the C md5 functions with the same names in the digest library. This error has been
observed on Linux clusters running Red Hat Enterprise Linux Workstation release 6.4 and 
CentOS release 6.6. It has not been observed on Mac. (Rhipe does not run on Windows.)

The bug can be observed in the following way:
```
# start fresh R session
library(rJava)
library(codetools)
 
library(Rhipe)
digest::digest("a") == digest::digest("b") # this should be FALSE but it returns TRUE
```

Restart R with a fresh session  and do this:
```
library(rJava)
library(codetools)
 
digest::digest("a") == digest::digest("b") # will be FALSE
library(Rhipe)
digest::digest("a") == digest::digest("b") # FALSE again as it should be
```

This bug can result in non-unique key hashes in datadr ddf and ddo objects, which can
be tested like this:

```
# x is a ddf
length(attributes(x)$ddo$keyHashes) # number of data divisions
any(duplicated(attributes(x)$ddo$keyHashes)) # TRUE = error
```

This bug can also result in error messages of the following type in Trelliscope from the makeDisplay function:
`Error in panelContent[[i]] : subscript out of bounds`.

**Comment by saptarshiguha** [comment]
had written package (rterra) which is a Lua language extension with
LLVM based AOT compilation. Using this the R author could call out to
Lua/Terra code which could also call out to C functions.

My goal was to take advantage of RHIPE's C code from Lua. See
[2] for an example​ and write MR jobs in lua/rterra ​
But for Lua functions in the rterra package to
call RHIPE's C functions, I had to set 'local' to FALSE in

https://github.com/tesseradata/RHIPE/blob/master/src/main/R/zzz.R#L11

This shares functions across namespaces. Maybe not the safest
idea. This is likely causing the problem.

It would be nice to have this option though. I'm okay if everyone
feels it should changed to TRUE
