### ISSUE TITLE
When attempting to run RHipe 0.75.2 i get a CNF error for org.apache.commons.LogFactory

### ISSUE THREAD

**Issue by sfines** [tesseradata/RHIPE#41]
I have tried this with the main branch and when I run Rhinit() I get the following error: 

```
> library(Rhipe)
Loading required package: codetools
Loading required package: rJava
Rhipe: HADOOP_BIN is missing, using $HADOOP/bin
------------------------------------------------
| Please call rhinit() else RHIPE will not run |
------------------------------------------------
> rhinit()
Rhipe: Using Rhipe.jar file
Initializing Rhipe v0.75.2
Error in .jnew("org/godhuli/rhipe/PersonalServer") : 
  java.lang.NoClassDefFoundError: org/apache/commons/logging/LogFactory


```

**Comment by myeggo** [comment]
I am having the same issue.  Do we have a solution for it?  It will be very appreciated if someone can provide help.

**Comment by hafen** [comment]
Sorry for the delay. This is most likely due to a configuration issue. Unfortunately these things can be difficult to debug since there is so much variability across systems.

In your R session, what do you get when you run `Sys.getenv("HADOOP_LIBS")`?

If there's nothing in that environment variable, if you are using bash, I'd try creating this environment variable with something like this:

```bash
export HADOOP_LIBS=`hadoop classpath | tr -d '*'`
```

And see if that gets you somewhere.

**Comment by herychemo** [comment]
Thank you hafen, that is the solution !!! 😄

**Comment by hafen** [comment]
Great!

**Comment by Wfore0990** [comment]
This saved me from my error as well! Thanks hafen!

In my situation I am trying to use Rhipe with Rstudio in a container and had to add the paths that ```hadoop classpath | tr -d '*'``` returns to my Renviron file.

**Comment by magicps5** [comment]
I'm still having same errors.

Loading required package: codetools
Loading required package: rJava
------------------------------------------------
| Please call rhinit() else RHIPE will not run |
------------------------------------------------
> rhinit()
Rhipe: Using Rhipe.jar file
Initializing Rhipe v0.75.2
Error in .jnew("org/godhuli/rhipe/PersonalServer") : 
  java.lang.NoClassDefFoundError: org/apache/commons/logging/LogFactory
> Sys.getenv("HADOOP_LIBS")
[1] "hadoop classpath | tr -d '*'"
