### ISSUE TITLE
RHIPE for windows

### ISSUE THREAD

**Issue by aglsharad** [tesseradata/RHIPE#43]
I am trying to install RHIPE on windows through RStudio but I am getting error - "ERROR: Unix-only package". 
Is RHIPE not available for windows? 

I downloaded RHIPE package (Rhipe_0.74.0.tar.gz) from http://tessera.io/docs-RHIPE/ and tried to install it. I installed packages "testdata" and "rjava" also.
For hadoop, I created virtual box and used Cloudera Hadoop VM.

**Comment by hafen** [comment]
Unfortunately RHIPE is not available for Windows.  If you are running a Linux VM on Windows you need to install RHIPE inside the VM.

**Comment by aglsharad** [comment]
Thanks Hafen.
